packages:
  - 'packages/*'
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@babel/*'
allowBuilds:
  esbuild: true
  protobufjs: true
  rolldown: true
  rollup: true
  sharp: true
  sqlite3: true
  unrs-resolver: true
  workerd: true
