name: deploy-website

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  setup-build-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Install pnpm
      uses: pnpm/action-setup@v6

    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 26
        cache: pnpm

    - name: Enable Corepack
      run: corepack enable

    - name: Install Modules
      run: pnpm install

    - name: Build Website
      run: pnpm website:build

    - name: Publish to Cloudflare Pages
      uses: cloudflare/wrangler-action@v4
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy packages/website/site/dist --project-name=cacheableorg --branch=main
